extra_sources =\
  wideners/checkbox-widener,\
  wideners/scrollbar-texture-1.20.4,\
  wideners/selection-list-background-widener,\
  wideners/tooltip-widener

preprocessor.mc_version_number = 12004
preprocessor.rendering = GUI_GRAPHICS
preprocessor.checkbox_size = FONT
preprocessor.checkbox_change_handler =
preprocessor.scroll_directions = BOTH
