extra_sources =\
  wideners/checkbox-widener-1.21,\
  wideners/scrollbar-texture-1.20.5,\
  wideners/selection-list-background-widener,\
  wideners/tooltip-widener

minecraft.version.major = 1.21

preprocessor.mc_version_number = 12101
preprocessor.rendering = GUI_GRAPHICS
preprocessor.checkbox_size = FONT
preprocessor.checkbox_change_handler =
preprocessor.editbox_cursor_to_start_param =
preprocessor.transparent_menus =
preprocessor.scroll_directions = BOTH
